title: vahgon.dev
url: "https://vahgon.dev"
baseurl: ""

description: vahgon.dev

twitter_uname: vahgonn
github_uname:  vahgon
linkedin_uname: mullins-ian

email_str: ian [at] vahgon (dot) dev

current_year: 2026

highlighter: none
kramdown:
  syntax_highlighter: null

sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:categories/:title
  projects:
    output: true
    permalink: /:collection/:name

ignore_theme_config: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - LICENSE
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - scripts
  - package.json
  - gulpfile.js
  - yarn.lock
  
