title: vahgon.dev
email: ian@vahgon.dev
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://vahgon.dev"
twitter_username: vahgonn
github_username:  vahgon

highlighter: rouge

ignore_theme_config: BOOL

sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /:collection/:name

# Build settings
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - LICENSE
  - "*.gem"
  - Gemfile
  - Gemfile.lock
